import { promises as fs } from 'node:fs';
import path from 'node:path';
import { StripeEzConfig } from '../config/schema.js';

export interface EnvWriteInput {
  config: StripeEzConfig;
  secretKey: string;
  publishableKey?: string;
  webhookSecret?: string;
}

function assertSafeEnvVarName(name: string): void {
  if (!/^[A-Z_][A-Z0-9_]*$/.test(name)) {
    throw new Error(`Invalid environment variable name: ${name}`);
  }
}

export function renderEnv(input: EnvWriteInput): string {
  const lines: string[] = [];
  lines.push('# Generated by stripe-ez');
  lines.push(`STRIPE_SECRET_KEY=${input.secretKey}`);
  if (input.publishableKey) {
    lines.push(`STRIPE_PUBLISHABLE_KEY=${input.publishableKey}`);
  }
  if (input.webhookSecret) {
    lines.push(`STRIPE_WEBHOOK_SECRET=${input.webhookSecret}`);
  } else if (input.config.webhook) {
    lines.push(`# STRIPE_WEBHOOK_SECRET= # paste from: stripe listen --forward-to ${input.config.webhook.url}`);
  }

  if (input.config.portal) {
    lines.push('\n# Stripe Customer Portal');
    lines.push(`STRIPE_PORTAL_CONFIG_ID=${input.config.portal.configurationId}`);
  }

  if (input.config.tax) {
    lines.push('\n# Stripe Tax');
    lines.push(`STRIPE_TAX_BEHAVIOR=${input.config.tax.behavior}`);
  }

  for (const product of input.config.products) {
    lines.push(`\n# ${product.name}`);
    for (const price of product.prices) {
      assertSafeEnvVarName(price.envVarName);
      lines.push(`${price.envVarName}=${price.stripePriceId}`);
    }
  }

  return `${lines.join('\n')}\n`;
}

export async function writeEnvFile(content: string, cwd = process.cwd()): Promise<void> {
  const envPath = path.join(cwd, '.env');
  await fs.writeFile(envPath, content, { encoding: 'utf8', mode: 0o600 });
}
